### PR TITLE
Fixes

### LINKED ISSUE #37: Wrong text in calendar registration
Currently the calendar contains the text "What have you been doing?" as the text input label. This should not be the case since we are planning to do something and have not done it yet.

Seems like the view is missing proper translation variables and has instead copied the ones used in activity registrator.

### LINKED ISSUE #39: Calendar localization
The calendar was created right before we had proper localization. The time strings need to be localized before displaying.

This possibly includes:

* From and to times
* Month and year

### LINKED ISSUE #41: Wrong translation
"Värderingar" (sv) is translated to "Evaluation" (en). This is not a correct translation since "Evaluation" (en) means "Utvärdering" (sv).
A more correct translation would be "Values" (en) or "Valuations" (en - might be an odd inflection).

### LINKED ISSUE #43: Typing for languages
The language component currently has no types. It would be nice to have both for autocompletion and to make sure nothing breaks if we change something.

### PR DESCRIPTION
**Pull request by EMattfolk**
This pull request fixes some small bugs and makes the code more consistent across the whole repo.

Co-authored-by: malin-mallan <malin-mallan@users.noreply.github.com>

### CODE REVIEW

**Review by LukasJonsson99 — APPROVED** [review]
Read the commits and ran the code on iOS and it looks good!

File: src/intl_android.tsx [hunk 1]
```diff
@@ -1,55 +1,55 @@
...
+  require('@formatjs/intl-displaynames/locale-data/en.js');
+  require('@formatjs/intl-listformat/locale-data/en.js');
+  require('@formatjs/intl-numberformat/locale-data/en.js');
+  require('@formatjs/intl-relativetimeformat/locale-data/en.js');
+  require('@formatjs/intl-datetimeformat/locale-data/en.js');
+
+  // TODO: Figure out why TS is mad
+  if ('__setDefaultTimeZone' in Intl.DateTimeFormat) {
+    // @ts-ignore TODO: Find proper fix for this. This line of code works.
+      Intl.DateTimeFormat.__setDefaultTimeZone( // <-- 'Never' type causes problems
```
Comment (Neathan) [inline src/intl_android.tsx]:
```suggestion
    Intl.DateTimeFormat.__setDefaultTimeZone( // <-- 'Never' type causes problems
```

**Review by Neathan — APPROVED** [review]
Looks great!
I think the change from json was good choice.
